### PR TITLE
Create floor-branch prefabs

### PR DESCRIPTION
**Pull request by arejayelle**
## Info
Issue: #34 #35 #36 
### Description
Create floor-branch prefabs

## Changes
- Add tilemap packages to project
- Create a Floor tile prefab (Currently just a cube)
- Add 6 different floor branch prefabs

## Note to reviewers
These are not implemented in a scene but can be easily. 
- Create an obj w/ a `Grid` component 
- Set the Grid's `Cell Swizzle` to XZY
- Drag in the branch prefab in as the child
Alt
- Add a tilemap as shown below
  - image
- Delete the tilemap and drag in the branch

### CODE REVIEW

**Review by po-trottier — CHANGES_REQUESTED** [review]
Few comments:
- It would be good to rename "pre-Ground" to something more descriptive live "FloorTile"
- That same prefab has a rotation in its transform... Should probably reset the transform on it!
- You will probably want to rotate your Tilemaps 90deg in the X axis so they are in the right orientation
image

**Comment by arejayelle** [comment]
> Few comments:
> 
> * It would be good to rename "pre-Ground" to something more descriptive live "FloorTile"
> * That same prefab has a rotation in its transform... Should probably reset the transform on it!
> * You will probably want to rotate your Tilemaps 90deg in the X axis so they are in the right orientation
>   image

1) `pre-ground` is because it's the ground prefab I could rename it
2) Good catch on the prefab transform, will reset
3) The Grid is meant to have `Cell Swizzle` set to `XZY` instead of the default `XYZ`, this fixes it

**Comment by po-trottier** [comment]
> > Few comments:
> > 
> > * It would be good to rename "pre-Ground" to something more descriptive live "FloorTile"
> > * That same prefab has a rotation in its transform... Should probably reset the transform on it!
> > * You will probably want to rotate your Tilemaps 90deg in the X axis so they are in the right orientation
> >   image
> 
> 1. `pre-ground` is because it's the ground prefab I could rename it
> 2. Good catch on the prefab transform, will reset
> 3. The Grid is meant to have `Cell Swizzle` set to `XZY` instead of the default `XYZ`, this fixes it

For point 3 it's mostly visually in the editor. The Tilemap grid appears vertically without the transform. I know it still works without the rotation but it's more intuitive and useful if the tilemap grid is in the same orientation as the tiles you're setting up

**Comment by arejayelle** [comment]
> > > Few comments:
> > > 
> > > * It would be good to rename "pre-Ground" to something more descriptive live "FloorTile"
> > > * That same prefab has a rotation in its transform... Should probably reset the transform on it!
> > > * You will probably want to rotate your Tilemaps 90deg in the X axis so they are in the right orientation
> > >   [img]
> > 
> > 
> > 
> > 1. `pre-ground` is because it's the ground prefab I could rename it
> > 2. Good catch on the prefab transform, will reset
> > 3. The Grid is meant to have `Cell Swizzle` set to `XZY` instead of the default `XYZ`, this fixes it
> 
> For point 3 it's mostly visually in the editor. The Tilemap grid appears vertically without the transform. I know it still works without the rotation but it's more intuitive and useful if the tilemap grid is in the same orientation as the tiles you're setting up

Double check your settings because, on my machine, the tilemap grid is aligned with the blocks i'm setting down

image

**Comment by po-trottier** [comment]
The grid in the branch prefabs are all 90deg rotated

image

**Comment by arejayelle** [comment]
> The grid in the branch prefabs are all 90deg rotated
> 
>[Image]

That is as intended. 
But that's because the tilemap alone is lacking the context of being inside of a `Grid` This prefab is made to be dragged into a grid, to give the context. But sure, 
Rotated everything by 90 degrees in 11d988fdc5f694733f9e413145158e11495959b6

**Review by po-trottier — APPROVED** [review]
Looks good!

**Pull request merged**
