### PR TITLE
Pause, Power-Up & Regular/Empowered Menus

### PR DESCRIPTION
**Pull request by itsShaVawn**
Both are in the GameUI prefab.

Toggle the visibility for PowerUpMenu to view it.

**Getting the font and icons from another branch**

**I had also previously written some scripts, but they are also in another branch.**

### CODE REVIEW

**Comment by itsShaVawn** [comment]
I have 2 options for the background of the Power-up menu:
image
image

**Review by po-trottier — DISMISSED** [review]

**Comment by po-trottier** [comment]
Merge conflicts

**Comment by itsShaVawn** [comment]
Updated images
image
image
image
image

**Review by daniela-venuta — CHANGES_REQUESTED** [review]
There is a typo in strength in the Power Up menu, also is it possible to make the increases reference something in the Game Manager or something in case we want to change the values? Also not sure why we have 4 squares in the pause menu? Otherwise looks fantastic, just a couple of things to change

**Comment by itsShaVawn** [comment]
> 

I kinda thought that 1 for each is multiple, hence why I put spells. But, definitely I can change that. Pretty quick fix.

**Comment by itsShaVawn** [comment]
> > There is a typo in strength in the Power Up menu, also is it possible to make the increases reference something in the Game Manager or something in case we want to change the values? Also not sure why we have 4 squares in the pause menu? Otherwise looks fantastic, just a couple of things to change
> 
> Also I think it should be Choose A Spell instead of Choose Your Spells because we only choose 1 of each

I kinda thought that 1 for each is multiple, hence why I put spells. But, definitely I can change that. Pretty quick fix.

**Comment by itsShaVawn** [comment]
> There is a typo in strength in the Power Up menu, also is it possible to make the increases reference something in the Game Manager or something in case we want to change the values? Also not sure why we have 4 squares in the pause menu? Otherwise looks fantastic, just a couple of things to change

Yep, I will take care of this. It was mainly to show the card and if the team was ok with this sort of description.

**Comment by daniela-venuta** [comment]
> > There is a typo in strength in the Power Up menu, also is it possible to make the increases reference something in the Game Manager or something in case we want to change the values? Also not sure why we have 4 squares in the pause menu? Otherwise looks fantastic, just a couple of things to change
> 
> Yep, I will take care of this. It was mainly to show the card and if the team was ok with this sort of description. The 4 squares in the pause menu so that the player can check their current spells/powers/buffs?

The thing is for the buff, they keep it until they die. Maybe what we can do instead is have each of them there and add a counter? if not maybe just not showing the power up because it wont reflect the history

**Comment by emilie-martin** [comment]
just a couple of things to note:
1) is there a way to make the icons square? they were meant to be square but they don't look square to me rn
2) can you use the button font (ZENANTIQUE) for the buttons on the pause menu? just for the sake of consistency
3) is there a way to put a smoother border on the spell cards somehow? color squares seem kind of block-y to me :/

**Comment by po-trottier** [comment]
Shouldn't the "titles" (spell names & power up names) be bold as well ?

**Comment by emilie-martin** [comment]
**reminder** to also change the text in the MainMenu.scene to have the ControlCanvas read "normal" and "empowered" spells to replace our internal "weak/strong" terminology (it's a remainder from my menu pr that we decided to implement into yours; hope you don't mind!)

**Review by daniela-venuta — DISMISSED** [review]

**Review by arejayelle — APPROVED** [review]
Looks good

**Pull request merged**
